services:
  db:
    image: postgres:15-alpine
    container_name: music_bot_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: music_bot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d music_bot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: music_bot
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=secret123
      - DB_NAME=music_bot_db
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: